name: bHub
version: 1.0.3-SNAPSHOT
main: io.github.bradnn.bHub
authors: [Bradn]
description: A simple to use hub plugin.

softdepend: [PlaceholderAPI]

commands:
  hub:
    description: Main Command.
    usage: /hub
